### ISSUE TITLE
WsPay method not visible

### ISSUE THREAD

**Issue by espacious** [ivantusek/WSPay#1]
Hi,

i installed your module but the payment method is not visible in Prestashop Front Office.
In backoffice all seems ok, do you have some advice for me? I use PS 1.7.3.1, PHP Version 5.6.38

Možemo i na Hrvatski, moja mail adresa je spc2spc(at)gmail.com

Puno hvala.

**Comment by ivantusek** [comment]
Hi,

The plugin was made for a smaller version at the time it came out PS 1.6.

Best regards.
